In [1]:
import pandas as pd

In [4]:
df = pd.read_excel('data/owid-covid-data.xlsx')

In [5]:
df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383793,ZWE,Africa,Zimbabwe,2024-02-28,266355.0,0.0,0.714,5739.0,0.0,0.286,...,30.7,36.791,1.7,61.49,0.571,16320539,NaN,NaN,NaN,NaN
383794,ZWE,Africa,Zimbabwe,2024-02-29,266355.0,0.0,0.714,5739.0,0.0,0.286,...,30.7,36.791,1.7,61.49,0.571,16320539,NaN,NaN,NaN,NaN
383795,ZWE,Africa,Zimbabwe,2024-03-01,266355.0,0.0,0.714,5739.0,0.0,0.286,...,30.7,36.791,1.7,61.49,0.571,16320539,NaN,NaN,NaN,NaN
383796,ZWE,Africa,Zimbabwe,2024-03-02,266355.0,0.0,0.714,5739.0,0.0,0.286,...,30.7,36.791,1.7,61.49,0.571,16320539,NaN,NaN,NaN,NaN
383797,ZWE,Africa,Zimbabwe,2024-03-03,266358.0,3.0,0.429,5740.0,1.0,0.143,...,30.7,36.791,1.7,61.49,0.571,16320539,NaN,NaN,NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383798 entries, 0 to 383797
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    383798 non-null  object
 1   continent                                   365438 non-null  object
 2   location                                    383798 non-null  object
 3   date                                        383798 non-null  object
 4   total_cases                                 344917 non-null  float64
 5   new_cases                                   372892 non-null  float64
 6   new_cases_smoothed                          371662 non-null  float64
 7   total_deaths                                322777 non-null  float64
 8   new_deaths                                  373187 non-null  float64
 9   new_deaths_smoothed                         371957 non-null  float64
 10  total_cases_per_million                     344917 non-null  float64
 11  new_cases_per_million                       372892 non-null  float64
 12  new_cases_smoothed_per_million              371662 non-null  float64
 13  total_deaths_per_million                    322777 non-null  float64
 14  new_deaths_per_million                      373187 non-null  float64
 15  new_deaths_smoothed_per_million             371957 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                38563 non-null   float64
 18  icu_patients_per_million                    38563 non-null   float64
 19  hosp_patients                               40086 non-null   float64
 20  hosp_patients_per_million                   40086 non-null   float64
 21  weekly_icu_admissions                       10653 non-null   float64
 22  weekly_icu_admissions_per_million           10653 non-null   float64
 23  weekly_hosp_admissions                      24098 non-null   float64
 24  weekly_hosp_admissions_per_million          24098 non-null   float64
 25  total_tests                                 79387 non-null   float64
 26  new_tests                                   75403 non-null   float64
 27  total_tests_per_thousand                    79387 non-null   float64
 28  new_tests_per_thousand                      75403 non-null   float64
 29  new_tests_smoothed                          103965 non-null  float64
 30  new_tests_smoothed_per_thousand             103965 non-null  float64
 31  positive_rate                               95927 non-null   float64
 32  tests_per_case                              94348 non-null   float64
 33  tests_units                                 106788 non-null  object
 34  total_vaccinations                          83070 non-null   float64
 35  people_vaccinated                           78974 non-null   float64
 36  people_fully_vaccinated                     75848 non-null   float64
 37  total_boosters                              51265 non-null   float64
 38  new_vaccinations                            68838 non-null   float64
 39  new_vaccinations_smoothed                   189718 non-null  float64
 40  total_vaccinations_per_hundred              83070 non-null   float64
 41  people_vaccinated_per_hundred               78974 non-null   float64
 42  people_fully_vaccinated_per_hundred         75848 non-null   float64
 43  total_boosters_per_hundred                  51265 non-null   float64
 44  new_vaccinations_smoothed_per_million       189718 non-null  float64
 45  new_people_vaccinated_smoothed              187129 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  187129 non-null  float64
 47  stringency_index                            197292 non-null  float64
 48  population_density                          326259 non-null  float64
 49  median_age                                  303288 non-null  float64
 50  aged_65_older                               292819 non-null  float64
 51  aged_70_older                               300248 non-null  float64
 52  gdp_per_capita                              297374 non-null  float64
 53  extreme_poverty                             191678 non-null  float64
 54  cardiovasc_death_rate                       297944 non-null  float64
 55  diabetes_prevalence                         313304 non-null  float64
 56  female_smokers                              223636 non-null  float64
 57  male_smokers                                220596 non-null  float64
 58  handwashing_facilities                      145975 non-null  float64
 59  hospital_beds_per_thousand                  263156 non-null  float64
 60  life_expectancy                             353448 non-null  float64
 61  human_development_index                     288975 non-null  float64
 62  population                                  383798 non-null  int64
 63  excess_mortality_cumulative_absolute        13142 non-null   float64
 64  excess_mortality_cumulative                 13142 non-null   float64
 65  excess_mortality                            13142 non-null   float64
 66  excess_mortality_cumulative_per_million     13142 non-null   float64
dtypes: float64(61), int64(1), object(5)
memory usage: 196.2+ MB

In [7]:
df_deaths = pd.read_excel('data/CovidDeaths.xlsx')

In [24]:
df_deaths

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million
0,AFG,Asia,Afghanistan,2020-01-05,41128772,0.0,0.0,0.000,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,AFG,Asia,Afghanistan,2020-01-06,41128772,0.0,0.0,0.000,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,AFG,Asia,Afghanistan,2020-01-07,41128772,0.0,0.0,0.000,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AFG,Asia,Afghanistan,2020-01-08,41128772,0.0,0.0,0.000,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AFG,Asia,Afghanistan,2020-01-09,41128772,0.0,0.0,0.000,0.0,0.0,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383793,ZWE,Africa,Zimbabwe,2024-02-28,16320539,266355.0,0.0,0.714,5739.0,0.0,...,0.018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
383794,ZWE,Africa,Zimbabwe,2024-02-29,16320539,266355.0,0.0,0.714,5739.0,0.0,...,0.018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
383795,ZWE,Africa,Zimbabwe,2024-03-01,16320539,266355.0,0.0,0.714,5739.0,0.0,...,0.018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
383796,ZWE,Africa,Zimbabwe,2024-03-02,16320539,266355.0,0.0,0.714,5739.0,0.0,...,0.018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
383797,ZWE,Africa,Zimbabwe,2024-03-03,16320539,266358.0,3.0,0.429,5740.0,1.0,...,0.009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
df_deaths = df_deaths.fillna(0)

In [26]:
df_deaths.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383798 entries, 0 to 383797
Data columns (total 26 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   iso_code                            383798 non-null  object
 1   continent                           383798 non-null  object
 2   location                            383798 non-null  object
 3   date                                383798 non-null  object
 4   population                          383798 non-null  int64
 5   total_cases                         383798 non-null  float64
 6   new_cases                           383798 non-null  float64
 7   new_cases_smoothed                  383798 non-null  float64
 8   total_deaths                        383798 non-null  float64
 9   new_deaths                          383798 non-null  float64
 10  new_deaths_smoothed                 383798 non-null  float64
 11  total_cases_per_million             383798 non-null  float64
 12  new_cases_per_million               383798 non-null  float64
 13  new_cases_smoothed_per_million      383798 non-null  float64
 14  total_deaths_per_million            383798 non-null  float64
 15  new_deaths_per_million              383798 non-null  float64
 16  new_deaths_smoothed_per_million     383798 non-null  float64
 17  reproduction_rate                   383798 non-null  float64
 18  icu_patients                        383798 non-null  float64
 19  icu_patients_per_million            383798 non-null  float64
 20  hosp_patients                       383798 non-null  float64
 21  hosp_patients_per_million           383798 non-null  float64
 22  weekly_icu_admissions               383798 non-null  float64
 23  weekly_icu_admissions_per_million   383798 non-null  float64
 24  weekly_hosp_admissions              383798 non-null  float64
 25  weekly_hosp_admissions_per_million  383798 non-null  float64
dtypes: float64(21), int64(1), object(4)
memory usage: 76.1+ MB

In [29]:
df_deaths.to_csv('data/CovidDeaths.csv', index=False)

In [28]:
df_deaths.to_excel('data/CovidDeaths.xlsx')

In [10]:
df_vaccinations = pd.read_excel('data/CovidVaccinations.xlsx')

In [23]:
df_vaccinations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383798 entries, 0 to 383797
Data columns (total 45 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    383798 non-null  object
 1   continent                                   383798 non-null  object
 2   location                                    383798 non-null  object
 3   date                                        383798 non-null  object
 4   total_tests                                 383798 non-null  float64
 5   new_tests                                   383798 non-null  float64
 6   total_tests_per_thousand                    383798 non-null  float64
 7   new_tests_per_thousand                      383798 non-null  float64
 8   new_tests_smoothed                          383798 non-null  float64
 9   new_tests_smoothed_per_thousand             383798 non-null  float64
 10  positive_rate                               383798 non-null  float64
 11  tests_per_case                              383798 non-null  float64
 12  tests_units                                 383798 non-null  object
 13  total_vaccinations                          383798 non-null  float64
 14  people_vaccinated                           383798 non-null  float64
 15  people_fully_vaccinated                     383798 non-null  float64
 16  total_boosters                              383798 non-null  float64
 17  new_vaccinations                            383798 non-null  float64
 18  new_vaccinations_smoothed                   383798 non-null  float64
 19  total_vaccinations_per_hundred              383798 non-null  float64
 20  people_vaccinated_per_hundred               383798 non-null  float64
 21  people_fully_vaccinated_per_hundred         383798 non-null  float64
 22  total_boosters_per_hundred                  383798 non-null  float64
 23  new_vaccinations_smoothed_per_million       383798 non-null  float64
 24  new_people_vaccinated_smoothed              383798 non-null  float64
 25  new_people_vaccinated_smoothed_per_hundred  383798 non-null  float64
 26  stringency_index                            383798 non-null  float64
 27  population_density                          383798 non-null  float64
 28  median_age                                  383798 non-null  float64
 29  aged_65_older                               383798 non-null  float64
 30  aged_70_older                               383798 non-null  float64
 31  gdp_per_capita                              383798 non-null  float64
 32  extreme_poverty                             383798 non-null  float64
 33  cardiovasc_death_rate                       383798 non-null  float64
 34  diabetes_prevalence                         383798 non-null  float64
 35  female_smokers                              383798 non-null  float64
 36  male_smokers                                383798 non-null  float64
 37  handwashing_facilities                      383798 non-null  float64
 38  hospital_beds_per_thousand                  383798 non-null  float64
 39  life_expectancy                             383798 non-null  float64
 40  human_development_index                     383798 non-null  float64
 41  excess_mortality_cumulative_absolute        383798 non-null  float64
 42  excess_mortality_cumulative                 383798 non-null  float64
 43  excess_mortality                            383798 non-null  float64
 44  excess_mortality_cumulative_per_million     383798 non-null  float64
dtypes: float64(40), object(5)
memory usage: 131.8+ MB

In [19]:
df_vaccinations = df_vaccinations.fillna(0)

In [20]:
df_vaccinations

,iso_code,continent,location,date,total_tests,new_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,37.746,0.5,64.83,0.511,0.0,0.0,0.0,0.0
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,37.746,0.5,64.83,0.511,0.0,0.0,0.0,0.0
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,37.746,0.5,64.83,0.511,0.0,0.0,0.0,0.0
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,37.746,0.5,64.83,0.511,0.0,0.0,0.0,0.0
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,37.746,0.5,64.83,0.511,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383793,ZWE,Africa,Zimbabwe,2024-02-28,0.0,0.0,0.0,0.0,0.0,0.0,...,1.6,30.7,36.791,1.7,61.49,0.571,0.0,0.0,0.0,0.0
383794,ZWE,Africa,Zimbabwe,2024-02-29,0.0,0.0,0.0,0.0,0.0,0.0,...,1.6,30.7,36.791,1.7,61.49,0.571,0.0,0.0,0.0,0.0
383795,ZWE,Africa,Zimbabwe,2024-03-01,0.0,0.0,0.0,0.0,0.0,0.0,...,1.6,30.7,36.791,1.7,61.49,0.571,0.0,0.0,0.0,0.0
383796,ZWE,Africa,Zimbabwe,2024-03-02,0.0,0.0,0.0,0.0,0.0,0.0,...,1.6,30.7,36.791,1.7,61.49,0.571,0.0,0.0,0.0,0.0
383797,ZWE,Africa,Zimbabwe,2024-03-03,0.0,0.0,0.0,0.0,0.0,0.0,...,1.6,30.7,36.791,1.7,61.49,0.571,0.0,0.0,0.0,0.0

In [22]:
df_vaccinations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383798 entries, 0 to 383797
Data columns (total 45 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    383798 non-null  object
 1   continent                                   383798 non-null  object
 2   location                                    383798 non-null  object
 3   date                                        383798 non-null  object
 4   total_tests                                 383798 non-null  float64
 5   new_tests                                   383798 non-null  float64
 6   total_tests_per_thousand                    383798 non-null  float64
 7   new_tests_per_thousand                      383798 non-null  float64
 8   new_tests_smoothed                          383798 non-null  float64
 9   new_tests_smoothed_per_thousand             383798 non-null  float64
 10  positive_rate                               383798 non-null  float64
 11  tests_per_case                              383798 non-null  float64
 12  tests_units                                 383798 non-null  object
 13  total_vaccinations                          383798 non-null  float64
 14  people_vaccinated                           383798 non-null  float64
 15  people_fully_vaccinated                     383798 non-null  float64
 16  total_boosters                              383798 non-null  float64
 17  new_vaccinations                            383798 non-null  float64
 18  new_vaccinations_smoothed                   383798 non-null  float64
 19  total_vaccinations_per_hundred              383798 non-null  float64
 20  people_vaccinated_per_hundred               383798 non-null  float64
 21  people_fully_vaccinated_per_hundred         383798 non-null  float64
 22  total_boosters_per_hundred                  383798 non-null  float64
 23  new_vaccinations_smoothed_per_million       383798 non-null  float64
 24  new_people_vaccinated_smoothed              383798 non-null  float64
 25  new_people_vaccinated_smoothed_per_hundred  383798 non-null  float64
 26  stringency_index                            383798 non-null  float64
 27  population_density                          383798 non-null  float64
 28  median_age                                  383798 non-null  float64
 29  aged_65_older                               383798 non-null  float64
 30  aged_70_older                               383798 non-null  float64
 31  gdp_per_capita                              383798 non-null  float64
 32  extreme_poverty                             383798 non-null  float64
 33  cardiovasc_death_rate                       383798 non-null  float64
 34  diabetes_prevalence                         383798 non-null  float64
 35  female_smokers                              383798 non-null  float64
 36  male_smokers                                383798 non-null  float64
 37  handwashing_facilities                      383798 non-null  float64
 38  hospital_beds_per_thousand                  383798 non-null  float64
 39  life_expectancy                             383798 non-null  float64
 40  human_development_index                     383798 non-null  float64
 41  excess_mortality_cumulative_absolute        383798 non-null  float64
 42  excess_mortality_cumulative                 383798 non-null  float64
 43  excess_mortality                            383798 non-null  float64
 44  excess_mortality_cumulative_per_million     383798 non-null  float64
dtypes: float64(40), object(5)
memory usage: 131.8+ MB

In [30]:
df_vaccinations.to_csv('data/CovidVaccinations.csv', index=False)

In [ ]:
df_vaccinations.to_excel('data/CovidVaccinations.xlsx')