# importing libraries

In [1]:
import pandas as pd

# import csv file

In [20]:
df = pd.read_csv('data/owid-covid-data.csv')

In [21]:
df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383793,ZWE,Africa,Zimbabwe,2024-02-28,266355.0,0.0,0.714,5739.0,0.0,0.286,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
383794,ZWE,Africa,Zimbabwe,2024-02-29,266355.0,0.0,0.714,5739.0,0.0,0.286,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
383795,ZWE,Africa,Zimbabwe,2024-03-01,266355.0,0.0,0.714,5739.0,0.0,0.286,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
383796,ZWE,Africa,Zimbabwe,2024-03-02,266355.0,0.0,0.714,5739.0,0.0,0.286,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
383797,ZWE,Africa,Zimbabwe,2024-03-03,266358.0,3.0,0.429,5740.0,1.0,0.143,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN

# Creating a new df deaths with chosen columns

In [22]:
df_deaths = df[['iso_code', 'continent', 'location', 'date', 'population', 'total_cases', 
    'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths', 
    'new_deaths_smoothed', 'total_cases_per_million', 'new_cases_per_million', 
    'new_cases_smoothed_per_million', 'total_deaths_per_million', 
    'new_deaths_per_million', 'new_deaths_smoothed_per_million', 
    'reproduction_rate', 'icu_patients', 'icu_patients_per_million', 
    'hosp_patients', 'hosp_patients_per_million', 'weekly_icu_admissions', 
    'weekly_icu_admissions_per_million', 'weekly_hosp_admissions', 
    'weekly_hosp_admissions_per_million']].copy()

# Saving the df deaths as csv

In [23]:
df_deaths.to_csv('data/covid_deaths.csv', index=False)

---

# Creating a new df vaccination with chosen columns

In [24]:
df_vaccinations =df[['iso_code', 'continent', 'location', 'date', 'total_tests', 'new_tests', 
    'total_tests_per_thousand', 'new_tests_per_thousand', 'new_tests_smoothed', 
    'new_tests_smoothed_per_thousand', 'positive_rate', 'tests_per_case', 
    'tests_units', 'total_vaccinations', 'people_vaccinated', 
    'people_fully_vaccinated', 'total_boosters', 'new_vaccinations', 
    'new_vaccinations_smoothed', 'total_vaccinations_per_hundred', 
    'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred', 
    'total_boosters_per_hundred', 'new_vaccinations_smoothed_per_million', 
    'new_people_vaccinated_smoothed', 'new_people_vaccinated_smoothed_per_hundred', 
    'stringency_index', 'population_density', 'median_age', 'aged_65_older', 
    'aged_70_older', 'gdp_per_capita', 'extreme_poverty', 
    'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers', 
    'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand', 
    'life_expectancy', 'human_development_index', 
    'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative', 
    'excess_mortality', 'excess_mortality_cumulative_per_million']].copy()

# Saving the df vaccinations as csv

In [25]:
df_deaths.to_csv('data/covid_vaccinations.csv', index=False)

---